name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-pip \
            python3-dev \
            libcairo2 \
            libcairo2-dev \
            pkg-config \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libwebp-dev \
            libtiff5-dev \
            zlib1g-dev

      - name: Install Python dependencies
        run: |
          python3 -m pip install --break-system-packages --upgrade pip
          python3 -m pip install --break-system-packages -r requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest tests/ -v
